/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-04-08 15:35:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PatientHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  \r\n");
      out.write(" body {\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("    background: #fafafa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("    font-size: 1.1em;\r\n");
      out.write("    font-weight: 300;\r\n");
      out.write("    line-height: 1.7em;\r\n");
      out.write("    color: #999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a, a:hover, a:focus {\r\n");
      out.write("    color: inherit;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    transition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("    padding: 15px 10px;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 0;\r\n");
      out.write("    margin-bottom: 40px;\r\n");
      out.write("    box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-btn {\r\n");
      out.write("    box-shadow: none;\r\n");
      out.write("    outline: none !important;\r\n");
      out.write("    border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".line {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 1px;\r\n");
      out.write("    border-bottom: 1px dashed #ddd;\r\n");
      out.write("    margin: 40px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("i, span {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------------------------------------------------\r\n");
      out.write("    SIDEBAR STYLE\r\n");
      out.write("----------------------------------------------------- */\r\n");
      out.write(".wrapper {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: stretch;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar {\r\n");
      out.write("    min-width: 250px;\r\n");
      out.write("    max-width: 250px;\r\n");
      out.write("    background: #7386D5;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    transition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar.active {\r\n");
      out.write("    min-width: 80px;\r\n");
      out.write("    max-width: 80px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnstyle\r\n");
      out.write("{\r\n");
      out.write("\tbackground-color: #17a2b8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar.active .sidebar-header h3, #sidebar.active .CTAs {\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar.active .sidebar-header strong {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar ul li a {\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar.active ul li a {\r\n");
      out.write("    padding: 20px 10px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 0.85em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar.active ul li a i {\r\n");
      out.write("    margin-right:  0;\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-size: 1.8em;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar.active ul ul a {\r\n");
      out.write("    padding: 10px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar.active a[aria-expanded=\"false\"]::before, #sidebar.active a[aria-expanded=\"true\"]::before {\r\n");
      out.write("    top: auto;\r\n");
      out.write("    bottom: 5px;\r\n");
      out.write("    right: 50%;\r\n");
      out.write("    -webkit-transform: translateX(50%);\r\n");
      out.write("    -ms-transform: translateX(50%);\r\n");
      out.write("    transform: translateX(50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar .sidebar-header {\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    background: #6d7fcc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar .sidebar-header strong {\r\n");
      out.write("    display: none;\r\n");
      out.write("    font-size: 1.8em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar ul.components {\r\n");
      out.write("    padding: 20px 0;\r\n");
      out.write("    border-bottom: 1px solid #47748b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar ul li a {\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    font-size: 1.1em;\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("#sidebar ul li a:hover {\r\n");
      out.write("    color: #7386D5;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("}\r\n");
      out.write("#sidebar ul li a i {\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar ul li.active > a, a[aria-expanded=\"true\"] {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background: #6d7fcc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("a[data-toggle=\"collapse\"] {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a[aria-expanded=\"false\"]::before, a[aria-expanded=\"true\"]::before {\r\n");
      out.write("    content: '\\e259';\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 20px;\r\n");
      out.write("    font-family: 'Glyphicons Halflings';\r\n");
      out.write("    font-size: 0.6em;\r\n");
      out.write("}\r\n");
      out.write("a[aria-expanded=\"true\"]::before {\r\n");
      out.write("    content: '\\e260';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("ul ul a {\r\n");
      out.write("    font-size: 0.9em !important;\r\n");
      out.write("    padding-left: 30px !important;\r\n");
      out.write("    background: #6d7fcc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.CTAs {\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.CTAs a {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 0.9em !important;\r\n");
      out.write("    display: block;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.download {\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    color: #7386D5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.article, a.article:hover {\r\n");
      out.write("    background: #6d7fcc !important;\r\n");
      out.write("    color: #fff !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* ---------------------------------------------------\r\n");
      out.write("    CONTENT STYLE\r\n");
      out.write("----------------------------------------------------- */\r\n");
      out.write("#content {\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    min-height: 100vh;\r\n");
      out.write("    transition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* ---------------------------------------------------\r\n");
      out.write("    MEDIAQUERIES\r\n");
      out.write("----------------------------------------------------- */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    #sidebar {\r\n");
      out.write("        min-width: 80px;\r\n");
      out.write("        max-width: 80px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-left: -80px !important ;\r\n");
      out.write("    }\r\n");
      out.write("    a[aria-expanded=\"false\"]::before, a[aria-expanded=\"true\"]::before {\r\n");
      out.write("        top: auto;\r\n");
      out.write("        bottom: 5px;\r\n");
      out.write("        right: 50%;\r\n");
      out.write("        -webkit-transform: translateX(50%);\r\n");
      out.write("        -ms-transform: translateX(50%);\r\n");
      out.write("        transform: translateX(50%);\r\n");
      out.write("    }\r\n");
      out.write("    #sidebar.active {\r\n");
      out.write("        margin-left: 0 !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #sidebar .sidebar-header h3, #sidebar .CTAs {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #sidebar .sidebar-header strong {\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #sidebar ul li a {\r\n");
      out.write("        padding: 20px 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #sidebar ul li a span {\r\n");
      out.write("        font-size: 0.85em;\r\n");
      out.write("    }\r\n");
      out.write("    #sidebar ul li a i {\r\n");
      out.write("        margin-right:  0;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #sidebar ul ul a {\r\n");
      out.write("        padding: 10px !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #sidebar ul li a i {\r\n");
      out.write("        font-size: 1.3em;\r\n");
      out.write("    }\r\n");
      out.write("    #sidebar {\r\n");
      out.write("        margin-left: 0;\r\n");
      out.write("    }\r\n");
      out.write("    #sidebarCollapse span {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("  </style>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Raleway\" rel=\"stylesheet\">\r\n");
      out.write("<title>Employee Management Screen</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"wrapper\">\r\n");
      out.write("            <!-- Sidebar Holder -->\r\n");
      out.write("            <nav id=\"sidebar\">\r\n");
      out.write("                <div class=\"sidebar-header\">\r\n");
      out.write("                    <h3>Bootstrap Sidebar</h3>\r\n");
      out.write("                    <strong>BS</strong>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"list-unstyled components\">\r\n");
      out.write("                    <li class=\"active\">\r\n");
      out.write("                        <a href=\"#homeSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\">\r\n");
      out.write("                            &nbsp;&nbsp;<i class=\"fas fa-home\" style=\"color:white; text-decoration:none;\"></i>&nbsp;&nbsp;\r\n");
      out.write("                            Home\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"collapse list-unstyled\" id=\"homeSubmenu\" style=\"color:white;\">\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Home 1</a></li>\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Home 2</a></li>\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Home 3</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\" style=\"color:white; text-decoration:none;\">\r\n");
      out.write("                           &nbsp;&nbsp;<i class=\"fas fa-briefcase\"></i>&nbsp;&nbsp;\r\n");
      out.write("                            About\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"#pageSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\" style=\"color:white; text-decoration:none;\">\r\n");
      out.write("                            &nbsp;&nbsp;<i class=\"fas fa-user\"></i>&nbsp;&nbsp;\r\n");
      out.write("                            Patient Details\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"collapse list-unstyled\" id=\"pageSubmenu\">\r\n");
      out.write("                            <li><a href=\"newPatient\" style=\"color:white; text-decoration:none;\">Patient Entry</a></li>\r\n");
      out.write("                            <li><a href=\"editPatient\" style=\"color:white; text-decoration:none;\">Patient Update</a></li>\r\n");
      out.write("                            <li><a href=\"deletePatient\" style=\"color:white; text-decoration:none;\">Patient Delete</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                    \r\n");
      out.write("                     <a href=\"#DiagnosisSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\" style=\"color:white; text-decoration:none;\">\r\n");
      out.write("                            &nbsp;&nbsp;<i class=\"fas fa-diagnoses\"></i>&nbsp;&nbsp;\r\n");
      out.write("                            Diagnosis Details\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"collapse list-unstyled\" id=\"DiagnosisSubmenu\">\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Diagnosis Entry</a></li>\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Diagnosis Update</a></li>\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Patient Delete</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    \r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                    \r\n");
      out.write("                     <a href=\"#InjectionSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\" style=\"color:white; text-decoration:none;\">\r\n");
      out.write("                            &nbsp;&nbsp;<i class=\"fas fa-syringe\"></i>&nbsp;&nbsp;\r\n");
      out.write("                            Injection Details\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"collapse list-unstyled\" id=\"InjectionSubmenu\">\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Injection Entry</a></li>\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Injection Update</a></li>\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Injection Delete</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    \r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                    \r\n");
      out.write("                     <a href=\"#SpecialSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\" style=\"color:white; text-decoration:none;\">\r\n");
      out.write("                            &nbsp;&nbsp;<i class=\"fas fa-file-medical-alt\"></i>&nbsp;&nbsp;\r\n");
      out.write("                            Special Tests\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"collapse list-unstyled\" id=\"SpecialSubmenu\">\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Biochemistry Test</a></li>\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Colonoscopy Test</a></li>\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Gastroscopy Test</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    \r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                     <li>\r\n");
      out.write("                    \r\n");
      out.write("                     <a href=\"#GenaralSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\" style=\"color:white; text-decoration:none;\">\r\n");
      out.write("                            &nbsp;&nbsp;<i class=\"fas fa-notes-medical\"></i>&nbsp;&nbsp;\r\n");
      out.write("                            Genaral Tests\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"collapse list-unstyled\" id=\"GenaralSubmenu\">\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Blood Test</a></li>\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Urine Test</a></li>\r\n");
      out.write("                            <li><a href=\"#\" style=\"color:white; text-decoration:none;\">Stool Test</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    \r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                    \r\n");
      out.write("                    \t<a href=\"#\" style=\"color:white; text-decoration:none;\">\r\n");
      out.write("                           &nbsp;&nbsp;<i class=\"fas fa-procedures\"></i>&nbsp;&nbsp;\r\n");
      out.write("                            Sonography\r\n");
      out.write("                        </a>\r\n");
      out.write("                    \r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                     <li>\r\n");
      out.write("                    \r\n");
      out.write("                    \t<a href=\"#\" style=\"color:white; text-decoration:none;\">\r\n");
      out.write("                           &nbsp;&nbsp;<i class=\"fas fa-users\"></i>&nbsp;&nbsp;\r\n");
      out.write("                            Search By name\r\n");
      out.write("                        </a>\r\n");
      out.write("                    \r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                    \t<a href=\"#\" style=\"color:white; text-decoration:none;\">\r\n");
      out.write("                           &nbsp;&nbsp;<i class=\"fas fa-calendar-alt\"></i>&nbsp;&nbsp;\r\n");
      out.write("                            Search By date\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"list-unstyled CTAs\">\r\n");
      out.write("                    <li><a href=\"#\" class=\"download\">Search Docters</a></li>\r\n");
      out.write("                    <li><a href=\"https://bootstrapious.com/p/bootstrap-sidebar\" class=\"article\">Back to article</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class =\"conteiner fluid\" style=\"width:100%;\">\r\n");
      out.write("            <!-- Page Content Holder -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-12\">\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("                <nav class=\"navbar navbar-default\">\r\n");
      out.write("                    <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"navbar-header\" style=\"width:1000%\">\r\n");
      out.write("                            <button type=\"button\" id=\"sidebarCollapse\" class=\"btn btn-info navbar-btn\">\r\n");
      out.write("                                <i class=\"glyphicon glyphicon-align-left\"></i>\r\n");
      out.write("                                <span>Toggle Sidebar</span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                                <li><a href=\"#\" >Page</a></li>\r\n");
      out.write("                                <li><a href=\"#\" >Page</a></li>\r\n");
      out.write("                                <li><a href=\"#\" >Page</a></li>\r\n");
      out.write("                                <li><a href=\"#\" >Page</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("    <div class=\"row\">           \r\n");
      out.write("    <div class=\"col-sm-1\"></div>\r\n");
      out.write("    <div class=\"col-sm-10\">     \r\n");
      out.write("                \r\n");
      out.write("  <table class=\"table table-striped\">\r\n");
      out.write("  <thead>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"col\">Registration No.</th>\r\n");
      out.write("      <th scope=\"col\">Registration Date</th>\r\n");
      out.write("      <th scope=\"col\">First Name</th>\r\n");
      out.write("      <th scope=\"col\">Last Name</th>\r\n");
      out.write("      <th scope=\"col\">Address</th>\r\n");
      out.write("      <th scope=\"col\">Action</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\">1</th>\r\n");
      out.write("      <td>Mark</td>\r\n");
      out.write("      <td>Otto</td>\r\n");
      out.write("      <td>@mdo</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\t<div class=\"col-sm-1\"></div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>             \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<script defer src=\"https://use.fontawesome.com/releases/v5.0.9/js/all.js\" integrity=\"sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <script type=\"text/javascript\">\r\n");
      out.write("             $(document).ready(function () {\r\n");
      out.write("                 $('#sidebarCollapse').on('click', function () {\r\n");
      out.write("                     $('#sidebar').toggleClass('active');\r\n");
      out.write("                 });\r\n");
      out.write("             });\r\n");
      out.write("         </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/pages/PatientHome.jsp(452,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("patient");
      // /WEB-INF/pages/PatientHome.jsp(452,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/PatientHome.jsp(452,2) '${listPatient}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listPatient}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<tr>\r\n");
            out.write("                       \r\n");
            out.write("                       <th scope=\"row\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patient.registration_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</th>\r\n");
            out.write("                       <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patient.registration_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                       <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patient.first_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                       <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patient.last_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("                       <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patient.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t   <td><a href=\"editPatient?registration_no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patient.registration_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" class=\"btn btn-warning\" role=\"button\" aria-pressed=\"true\">Edit</a>\r\n");
            out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\t\t\t\t\t\t<a href=\"deletePatient?registration_no=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patient.registration_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" class=\"btn btn-danger\" role=\"button\" aria-pressed=\"true\">Delete</a>\r\n");
            out.write("\t\t\t\t\t\t</td>\r\n");
            out.write("\t\r\n");
            out.write("\t\t\t\t</tr>\r\n");
            out.write("   ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
